apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: binding-gateway-backend
spec:
  application:
    name: gateway
    group: apps
    version: v1
    resource: deployments
  services:
    - name: catalog
      group: ""
      version: v1
      kind: Service
    - name: inventory
      group: ""
      version: v1
      kind: Service
  detectBindingResources: true
  bindAsFiles: false
