apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
  labels:
    app: web
    app.kubernetes.io/name: web
    app.kubernetes.io/component: web-nodejs
data:
  COOLSTORE_GW_SERVICE: gateway
  OPENSHIFT_BUILD_NAMESPACE: test-multi-pods
