apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-multi-pods
commonLabels:
  app.kubernetes.io/part-of: coolstore
resources:
  - deploy-catalog.yaml
  - svc-catalog.yaml
  - deploy-inventory.yaml
  - svc-inventory.yaml
  - cm-gateway.yaml
  - deploy-gateway.yaml
  - svc-gateway.yaml
  - route-gateway.yaml
  - cm-web.yaml
  - deploy-web.yaml
  - svc-web.yaml
  - route-web.yaml
