apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: test-single-pod
spec:
  selector:
    app: web-coolstore
  ports:
    - name: web
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
