apiVersion: v1
kind: Secret
metadata:
  name: dockerconfig-secret
stringData:
  config.json: |
    {
      "auths" : {
        "quay.io": {
        "auth": "<YOUR_AUTH_TOKEN>"
        }
      }
    }
