apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: push-on-catalog
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[ci]"
    pipelinesascode.tekton.dev/task: "[git-clone, kaniko]"
    pipelinesascode.tekton.dev/task-1: "[.tekton/task/update-gitops-via-set.yaml]"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "push" && "catalog-spring-boot/***".pathChanged()
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: image_name
      value: "quay.io/rh-ee-yuewu/catalog-spring-boot"
    - name: image_tag
      value: "{{ revision }}"
    - name: context
      value: "catalog-spring-boot"
    - name: gitops_repo_url
      value: "https://github.com/lunarwhite/playground"
    - name: gitops_revision
      value: "config-ci"
    - name: gitops_config_dir
      value: "apps/catalog/overlays/stage"
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
    workspaces:
      - name: shared-workspace
      - name: registry-auth-secret
      - name: basic-auth
    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
        params:
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)
        workspaces:
          - name: output
            workspace: shared-workspace
      - name: build-push-image
        runAfter:
          - fetch-repository
        taskRef:
          name: kaniko
        params:
          - name: IMAGE
            value: $(params.image_name):$(params.image_tag)
          - name: CONTEXT
            value: $(params.context)
        workspaces:
          - name: source
            workspace: shared-workspace
          - name: dockerconfig
            workspace: registry-auth-secret
      - name: update-gitops-config
        runAfter:
          - build-push-image
        taskRef:
          name: update-gitops-via-set
        params:
          - name: url
            value: $(params.gitops_repo_url)
          - name: revision
            value: $(params.gitops_revision)
          - name: kustomization_dir
            value: $(params.gitops_config_dir)
          - name: image_name
            value: $(tasks.build-push-image.results.IMAGE_URL)
          - name: image_digest
            value: $(tasks.build-push-image.results.IMAGE_DIGEST)
        workspaces:
          - name: source
            workspace: shared-workspace
          - name: git-auth-secret
            workspace: basic-auth
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: registry-auth-secret
      secret:
        secretName: dockerconfig-secret
    - name: basic-auth
      secret:
        secretName: "{{ git_auth_secret }}"
